name: Smoke Tests - PR

on:
  pull_request:
    branches: [master]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Instalar o Chrome Driver
        uses: nanasess/setup-chromedriver@v1
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run Test
<<<<<<< HEAD
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci -Dcucumber.options="--tags @login-sucesso"
=======
        run:  mvn test -Dtest=RunCucumber -Dbrowser=chrome -Dcucumber.options="--tags @login-sucesso"
>>>>>>> 39a686938585fd2ba70d55d4335fad2ff4071f64

      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formated-report/'

      - name: Enviar notificação para o Slack - Sucesso
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON_EMOJI: https://www.flaticon.com/br/icone-gratis/aprovado_4157080
          SLACK_MESSAGE: 'Sucesso na execução de testes de PR :white_check_mark:'
          SLACK_TITLE: 'Sucesso na execução de testes de PR :white_check_mark:'
          SLACK_USERNAME: SUCESSO

      - name: Enviar notificação para o Slack - Falha
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON_EMOJI: https://pt.dreamstime.com/fotografia-de-stock-royalty-free-%C3%ADcone-do-erro-cr%C3%ADtico-image8363117
          SLACK_MESSAGE: 'Erro na execução de testes de PR :fire:'
          SLACK_TITLE: 'Erro na execução de testes de PR :fire:'
          SLACK_USERNAME: FALHA
